favicon: /img/favicon.png
# Change to your profile picture
avatar: /img/avatar.jpg
# if author sets in hexo_config, this string doesn't work
author: 'Ziqian Xu'
author_bio: ''

since: 2022

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  About: /about
  Publications: /publications
  Presentations: /presentations


# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/favicon.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  # fab fa-twitter: /
  # fab fa-facebook-square: /
  fab fa-github: https://github.com/shaosijing
  # fab fa-stack-overflow: /
  fab fa-linkedin: https://www.linkedin.com/in/sjshao/
  # fab fa-weibo: /
  # fab fa-weixin: /
  # fab fa-qq: /
  fas fa-envelope: sshao2@nd.edu
  # fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: https://scholar.google.com/citations?user=3NNG6HgAAAAJ&hl=en&oi=sra || fas fa-graduation-cap
  # ORCID: / || fab fa-orcid

# CV download link
cv_dl:
  enable: true
  dir: /attaches/ShaoCV.pdf
  description: My CV

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js